sudo: required
dist: trusty
addons:
    chrome: stable
language: node_js
node_js:
    - '11'
before_install:
    - npm i npm@^6 -g
install:
    - npm install
script:
    - npm run test-lib-ci
    - npm run build-lib
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
notifications:
    email: false
